spring:
  application:
    name: concert_booking

  datasource:
    url: jdbc:mysql://localhost:3306/concert_booking
    username: root
    password : root
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        default_batch_fetch_size: 30
        ## sql log
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console


  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
springdoc:
  use-fqn: true
